### ISSUE TITLE
Create Automated Build on Docker Hub

### ISSUE THREAD

**Issue by pataquets** [rapidloop/statsd-vis#5]
Docker Hub allows you to create Automated Builds from source: https://docs.docker.com/docker-hub/builds/
It would add another packaging/distribution/installation method, whose buildings would be triggered automatically on each commit. It also allows to create different image tags automatically from git tags & branches.
Also, documentation could include an example ```docker run``` command which would become the canonical, no-install-needed way to run latest statsd-vis.

By making the image build via an AB, you give the resulting image verifiability and auditability. Also, the build is fully automatic. You can have the latest image tag build from HEAD and individual image tags from git's release tags. Some people avoid non-verifiable (manually uploaded) images due to security & traceability reasons.

After #4 is in, just a free Docker Hub account and a quick setup would do. Ping me if you need help.

**Comment by mdevan** [comment]
Thanks for #4. Docker image now available as [rapidloop/statsd-vis](https://hub.docker.com/r/rapidloop/statsd-vis/).

**Comment by pataquets** [comment]
Awesome!
Awaiting to https://github.com/octo/statsd-tg/pull/2 to see if I can provide a suitable testing Docker Compose manifest.

**Comment by pataquets** [comment]
Sent docs PR #6 to make people aware.

**Comment by pataquets** [comment]
Closing solved issue. Pending improvement at #7 .
